---
title: "SSB Workshop - New Methods in Phylogenetics and Evolution"
author: "Dan Warren"
date: "6/21/2019"
output:
  html_document: 
    toc: TRUE
    toc_float: TRUE
---
 
# Workshop Description
Phylogenies form the foundation of our understanding of both the pattern and process of evolution on Earth.  Methods for inferring phylogenies and using them in comparative and macroevolutionary analyses are constantly improving, and it can prove difficult for even seasoned investigators in the field to keep pace.  In this workshop we will offer a collection of short (approximately one hour per topic) courses on a diverse array of new analytical methods.  

This workshop will be suitable for graduate students, postdocs, and senior faculty.  It is intended for users who are already familiar with R and have a good working knowledge of phylogenetics.  Attendees will be expected to bring a laptop with R and RStudio installed, and will be provided with a list of necessary R packages beforehand.


# Sections

###  1. Phylogenetic analysis with phangorn and ape
*Klaus Schliep, University of Massachusetts*

### 2. Macroevolutionary experimental design, using simulations to improvecomparative analyses
*Samantha Price, Clemson University*

### 3. Reproducible workflows for total-evidence dating analyses
*April Wright, Southeastern Louisiana University*

### 4. Comparative methods in the tidyverse
*Luke Harmon, University of Idaho*

### 5. Plotting trees against geologic time and generating phylomorphospaces from discrete character data using Claddis and strap
*Graeme Lloyd, University of Leeds*

### 6. Posterior predictive checks in Bayesian phylogenetics
*Tara Pelletier, Radford University*

### 7. Visualizing phylogenetic MCMC results with RWTY
*Dan Warren, Senckenberg Biodiversity and Climate Research Center*

Markov Chain Monte Carlo methods are among the most popular methods for inferring phylogenetic topologies and related phenomena.  However, MCMC analyses are only reliable if the MCMC chains have explored the space of possible solutions enough such that further exploration will not materially change the inferences being made from the data (termed "stationarity" or "convergence").  Determining whether or not this is the case is an ongoing challenge in phylogenetics.  In this session, we will explore RWTY, an R package for visualizing and diagnosing the behaviour of MCMC chains, with the goal of understanding when chains may, and may not, have reached convergence.

### 8. Analysis of discrete character evolution on phylogenies in R
*Liam Revell, University of Massachusetts*



